# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "ahusanovic1"
          server: "codd.cs.gsu.edu"
          ssh_private_key: ${{ secrets.SSH_CODD_SERVER }}
          local_path: "./static/*"
          remote_path: "/home/ahusanovic1/public_html"
          args: "-o ConnectTimeout=5"
